const SOUND_CLOUD_CLIENT_ID = 'bf79fe29f970e2e33518080b464fb1be'
const YOUTUBE_API_KEY = 'AIzaSyBBUXxtAlXI4mul2uevdqa6aNcfkmVPyII'

module.exports = {
  SOUND_CLOUD_CLIENT_ID: SOUND_CLOUD_CLIENT_ID,
  YOUTUBE_API_KEY: YOUTUBE_API_KEY
}