const SOUND_CLOUD_CLIENT_ID = 'YOUR_CLIENT_ID_HERE'
const YOUTUBE_API_KEY = 'YOUR_API_KEY_HERE'

module.exports = {
  SOUND_CLOUD_CLIENT_ID: SOUND_CLOUD_CLIENT_ID,
  YOUTUBE_API_KEY: YOUTUBE_API_KEY
}